### PR TITLE
fsck: revert repair zero size dir

### PR DESCRIPTION
**Pull request by YuezhangMo**
The zero-size directory is compliant with the exFAT specification, does not need repairing.
So we create this PR to revert the repair for zero-size directory.

In kernel size, we prepared https://patchwork.kernel.org/project/linux-fsdevel/list/?series=780105 to support zero-size directory.

### CODE REVIEW

**Comment by namjaejeon** [comment]
@Erichorng linux-exfat driver will handle zero size directory. The related patches have been applied to the following branch and mainline.

git clone https://github.com/namjaejeon/linux-exfat-oot

And your patches in exfatprogs will be reverted with this PR If you are okay.

**Comment by namjaejeon** [comment]
@hclee Please review these patches.

**Comment by hclee** [comment]
Looks good to me. 
But @Erichorng, is this okay to revert this commit?

**Comment by Erichorng** [comment]
Okay. 
Indeed, it's better to handle the problem in linux-exfat driver.

**Comment by namjaejeon** [comment]
Applied them to #exfat-next now! Thanks for your work!

**Pull request closed without merging**
