### PR TITLE
Include tests in dist tarball

### PR DESCRIPTION
**Pull request by aleasto**
Hi!

We would like to use your test cases when packaging downstream in Ubuntu.
What do you think about including them in the dist tarball?

### CODE REVIEW

**Comment by namjaejeon** [comment]
@aleasto
Are you package maintainer of Canonical(ubuntu) ? You haven't given any reason why it is needed. I am concerned that there may be more users who do not want to use this test image and this could increase the package size.

**Comment by aleasto** [comment]
Yes, I'm working for Canonical on Ubuntu.

`exfatprogs` is currently not shipped by default in Ubuntu (due to historical patent concerns over exfat, which have since changed) and we would like to change that.

It is required that any package shipped by default in Ubuntu provide a non-trivial testing suite, both at build time to verify that the build works correctly, as well as at CI tests to be run when other packages updates to verify that they do not cause a regression in this package. The test suite you provide seems well fit for this purpose.
N.B.: The test suite would not be shipped to the end users.

If you included the tests as part of the dist tarball we wouldn't have to track a diff from your tarball and manually synchronize the test suite when it changes. I'm also planning to propose adopting the same test suite in Debian.

**Comment by hclee** [comment]
@aleasto 
Is impossible to modify your build and test script? I think it is not easy to ask for all projects to include tests in dist tarball.

**Comment by aleasto** [comment]
> Is impossible to modify your build and test script? 

Build and test scripts cannot access the internet to download external resources: generally no packaging infrastructure would allow that for obvious security reasons. You can either publish the tests for distros to use, or we have to manually include them ourselves.

> I think it is not easy to ask for all projects to include tests in dist tarball.

Typically projects that have a test suite will make them available in a `make test` form. This is generally the case for Meson/CMake projects.
It might not be the norm for Automake projects, I'm not super familiar.
I'm not asking for the tests to be integrated in the build system, just that they are available in the tarball.

You don't *have to* do this; we can work around it with some extra work. But I suspect more distributions may appreciate having automated tests they can just run.

**Comment by jbicha** [comment]
@aleasto Perhaps another way to do this is to ask the Debian maintainer if they'd be willing to update debian/watch to use the automatic Github tag tarball instead of the release artifact. It wouldn't have the benefit of the gpg signed tarball though.

But I agree with you that the increased filesize of including the tests in the dist tarball is minimal, around 130K compressed. Most projects that have a testsuite do include it in their release tarballs.

**Comment by aleasto** [comment]
> @aleasto Perhaps another way to do this is to ask the Debian maintainer if they'd be willing to update debian/watch to use the automatic Github tag tarball instead of the release artifact. It wouldn't have the benefit of the gpg signed tarball though.
> 
> But I agree with you that the increased filesize of including the tests in the dist tarball is minimal, around 130K compressed. Most projects that have a testsuite do include it in their release tarballs.

Funnily enough the debian/watch file *was* pointing to the github tarball, but the debian maintainer was manually downloading the dist tarball instead. In the end we fixed the debian/watch file to point to the dist tarball and added a binary patch containing the `tests` folder (documenting how it was sourced so that it can be maintained with updates)

**Comment by namjaejeon** [comment]
The problem is that the tests directory in exfatprogs can grow in size. In the future, the dist tarball file will be several MB. Do e2fsprogs, xfsprogs, or btrfsprogs has such tests to the dist tarball?

**Comment by hclee** [comment]
e2fsprogs doesn't provide dist tarballs but only github tag tarballs. 

@aleasto 
as @jbicha said, how about asking for the debian mainainter to use the github tag tarballs instead of dist tarballs?

**Comment by namjaejeon** [comment]
@hclee 
> e2fsprogs doesn't provide dist tarballs but only github tag tarballs.

When releasing exfatprogs new version, You don't command 'make dist" ?

**Comment by hclee** [comment]
> @hclee
> 
> > e2fsprogs doesn't provide dist tarballs but only github tag tarballs.
> 
> When releasing exfatprogs new version, You don't command 'make dist" ?

I do "make distclean" and the tests directory is not included because Makefile.am's EXTRA_DIST

**Comment by namjaejeon** [comment]
Sigh.. It is the same. If so, you will not make distclean from the next version ?

**Comment by hclee** [comment]
> Sigh.. It is the same. If so, you will not make distclean from the next version ?

I know these have the same result. when releaseing, I do in the way below:
make distclean; ./autogen.sh; ./configure; make distcheck

**Comment by namjaejeon** [comment]
I understand that you will include tests directory in github tag tarball from next version.

**Comment by hclee** [comment]
> I understand that you will include tests directory in github tag tarball from next version.

Do you mean the dist tarball?
the github tag tarball already has tests directory, but the dist tarball doesn't because of Makefile.am

**Comment by namjaejeon** [comment]
Okay, got it.

Anyway, I couldn't find any reason to release a big size tarballs. I want to know how other filesystem utils do this.

**Comment by aleasto** [comment]
The e2fsprogs tarball is 7M: https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.1/
The btrfs-progs tarball is 3M: https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/
The dosfstools tarball is 0.3M: https://github.com/dosfstools/dosfstools/releases/tag/v4.2
The bcachefs-tools tarball is 1M: https://evilpiepirate.org/bcachefs-tools/
The xfsprogs tarball is 1M: https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/

All of them include tests (except xfsprogs which has no tests in git either)

**Comment by aleasto** [comment]
The issue with not using the dist tarball is that different autotools versions produce different results.
In extreme cases a newer autotools version might fail to `autoreconf` the project.
Here's the difference between your 1.2.4 dist tarball and the dist tarball I could reproduce on my Ubuntu 24.04 system:
https://aleasto.fedorapeople.org/exfatprogs/1.2.4_to_1.2.4.orig/changes_report.html

**Comment by namjaejeon** [comment]
I have checked that other tools also have test suites. I will apply this. Thank you.

**Comment by namjaejeon** [comment]
Applied it to #exfat-next now.

**Pull request closed without merging**
