### PR TITLE
mkfs: setting of the InUse bit of EntryType of Volume Label Entry

### LINKED ISSUE #230: Setting of the InUse bit of EntryType of Volume Label Entry
While using [The Sleuth Kit (TSK)](https://www.sleuthkit.org/sleuthkit/) to analyze flash drives formatted without a label using mkfs.exfat, I encountered this error:

> exfatfs_is_vol_label_dentry: incorrect volume label length

Which was caused by the label length check at [L128 of exfatfs_meta.c](https://github.com/sleuthkit/sleuthkit/blob/sleuthkit-4.12.0/tsk/fs/exfatfs_meta.c#L128) because the default value (0x83) of the EntryType in mkfs.c indicates that the Volume Label Entry is in use even if there is really no label provided when formatting:
https://github.com/exfatprogs/exfatprogs/blob/8593314715f4c0e531ee7cb26bdd4cd06e8a3f7f/mkfs/mkfs.c#L345
https://github.com/exfatprogs/exfatprogs/blob/8593314715f4c0e531ee7cb26bdd4cd06e8a3f7f/include/exfat_ondisk.h#L54

However, my understanding is that if the formatted volume does not have a label, the InUse bit of the EntryType should be set to 0 (i.e., EntryType should be 0x03) instead of 1 (0x83) according to Microsoft's exFAT specification[^1][^2]. Windows Disk Management does set this bit accordingly, so the TSK commands work fine with those formatted by Windows. Although TSK could improve their check for wider compatibility, I think it makes sense to also modify L345 in mkfs.c to something like:

`ed[0].type = ui->volume_label_len > 0 ? EXFAT_VOLUME : 0x03;`

Please let me know if this sounds a reasonable suggestion or if there is something obvious I missed. Thank you!

[^1]: https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#table-15-generic-entrytype-field-structure
[^2]: https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#6214-inuse-field).

### PR DESCRIPTION
**Pull request by jengbou**
This pull request closes #230

### CODE REVIEW

**Comment by namjaejeon** [comment]
Applied them to #exfat-next. Thanks!

**Comment by YuezhangMo** [comment]
The original implementation sets CharacterCount and VolumeLabel to 0. This is in compliance with the exfat specification, and I think the original implementation is fine.

```
At least 0, which means the Unicode string is 0 characters long (which is the equivalent of no volume label)
```

Even if the first entry is unused, `exfat_set_volume_label()` will not set the volume label to the first entry, but to the last unused entry. This may cause util-linux to fail to find the volume label, because util-linux only looks for the first 10000 entries(https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/libblkid/src/superblocks/exfat.c#n94).

I think

1. Setting the first entry as VolumeLabel can reduce the lookup.
2. Corrected the maximum number of search directory entries to 256×1024×1024/32=8388608 in util-linux.
3. It is better to set the volume label to the first unused entry if there is no volume label  entry.

**Comment by namjaejeon** [comment]
@YuezhangMo 

> Even if the first entry is unused, exfat_set_volume_label() will not set the volume label to the first entry, but to the last unused entry. 

Can you check how windows handle this ? Windows set volume label after finding last unused entry or use it after setting InUsed bit of first entry ? If it is the latter, we need to change exfat_set_volume_label().

> It is better to set the volume label to the first unused entry if there is no volume label entry.

Can we make same case in windows ? i.e. InUsed bit of volume label entry is enable and volume label length is zero.

> Corrected the maximum number of search directory entries to 256×1024×1024/32=8388608 in util-linux.

Okay. good catch.

**Comment by namjaejeon** [comment]
> At least 0, which means the Unicode string is 0 characters long (which is the equivalent of no volume label)

@jengbou Can you update "The Sleuth Kit" not to deal with it as an error?

**Comment by YuezhangMo** [comment]
@namjaejeon 

> Can you check how windows handle this ? Windows set volume label after finding last unused entry or use it after setting InUsed bit of first entry ? If it is the latter, we need to change exfat_set_volume_label().

Both Windows and exfat_set_volume_label() sets volume label to the last unused entry. But I still think that if there is no volume label entry, it is better to set the volume label to the first unused entry instead of the last unused entry.

I tried the following cases.

1. format without volume label in windows, the first entry is set to 0x03.
2. add a new volume label in windows, the first entry is still 0x03, the volume label is set to the last unused entry.
3. remove the volume label in windows, windows just set the entry type to 0x03, the other bytes are not changed.
4. add a new volume label in windows again, the volume label is set to the last unused entry too(there are 2 0x03 entries and a 0x83 entry).

> Can we make same case in windows ? i.e. InUsed bit of volume label entry is enable and volume label length is zero.

No, but Windows doesn't deal with it as an error.

I tried the following cases without this MR.

1. format without volume label in linux by `mkfs.exfat`, the first entry is set to 0x83, InUsed bit of volume label entry is enable and volume label length is zero.
2. add a new volume label in windows, the volume label is set to the first entry.
3. remove the volume label in windows, windows just set the entry type to 0x03, the other bytes are not changed.

**Comment by jengbou** [comment]
> The original implementation sets CharacterCount and VolumeLabel to 0. This is in compliance with the exfat specification, and I think the original implementation is fine.

I would say this statement is not entirely true. The original implementation is fine but not ideal as it's not in compliance with the exfat specification.

> 
> ```
> At least 0, which means the Unicode string is 0 characters long (which is the equivalent of no volume label)
> ```
> 

This is correct only for the CharacterCount Field, it does not automatically validate the EntryType Field, which needs to conform accordingly:

[7.3.1 EntryType Field](https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#731-entrytype-field) -> [6.3.1 EntryType Field; specifically 6.3.1.4](https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#631-entrytype-field) -> [6.2.1.4 InUse Field](https://learn.microsoft.com/en-us/windows/win32/fileio/exfat-specification#6214-inuse-field)


@namjaejeon 
> @jengbou Can you update "The Sleuth Kit" not to deal with it as an error?

I created an issue (sleuthkit/sleuthkit#2857) for compatibility reason. However, I would still say it's more prudent to stick to the Microsoft's specification (and compatible implementation).


> @namjaejeon
> 
> > Can you check how windows handle this ? Windows set volume label after finding last unused entry or use it after setting InUsed bit of first entry ? If it is the latter, we need to change exfat_set_volume_label().
> 
> Both Windows and exfat_set_volume_label() sets volume label to the last unused entry. But I still think that if there is no volume label entry, it is better to set the volume label to the first unused entry instead of the last unused entry.
> 
> I tried the following cases.
> 
> 1. format without volume label in windows, the first entry is set to 0x03.
> 2. add a new volume label in windows, the first entry is still 0x03, the volume label is set to the last unused entry.
> 3. remove the volume label in windows, windows just set the entry type to 0x03, the other bytes are not changed.
> 4. add a new volume label in windows again, the volume label is set to the last unused entry too(there are 2 0x03 entries and a 0x83 entry).

> 1. format without volume label in linux by `mkfs.exfat`, the first entry is set to 0x83, InUsed bit of volume label entry is enable and volume label length is zero.
> 2. add a new volume label in windows, the volume label is set to the first entry.
> 3. remove the volume label in windows, windows just set the entry type to 0x03, the other bytes are not changed.

I also went through the above steps while working on this and other issues. This is related to:
> 1. Setting the first entry as VolumeLabel can reduce the lookup.

I would think setting to the last unused root directory entry is more of a design preference. None of the tools, including Windows itself, can cover all the implementations/messing around by users, especially craftily messing it up to avoid detection. I guess Windows may have its own reason, e.g., history versioning, to not overwrite the first[^1] entry when updating/adding label afterward. So the least one can do is probably to stick to the exFAT specification for the initial formatting. And this is what this PR for.

[^1]: the first root directory entry or earliest valid volume label entry.

**Comment by namjaejeon** [comment]
@jengbou If original one is violating specification, Windows fsck should turn InUsed bit off of volume label entry that has 0 length...

@YuezhangMo I would like to know how other exfat-utils format it. i.e. https://github.com/relan/exfat

**Comment by jengbou** [comment]
> @jengbou If original one is violating specification, Windows fsck should turn InUsed bit off of volume label entry that has 0 length...
> 

@namjaejeon An empty label can exist in a valid volume label entry if it's the only volume label entry, so I am not sure I follow your comment above. Can you be more specific. Thanks!

**Comment by YuezhangMo** [comment]
@namjaejeon 
>  I would like to know how other exfat-utils format it. i.e. https://github.com/relan/exfat

 exfat-utils set volume label to the first unused entry.

I tried the following cases.

1. format without volume label, the first entry is set to 0x03.
2. add a new volume label, the volume label is set to the first entry.
3. remove the volume label, the entry type is set to 0x03, the other bytes are zeroed.

For the case of no volume label, I think it is better to set the first entry to 0x83, so that util-linux does not need to search the whole root directory, which will save a lot of time if the root directory is large.

**Comment by jengbou** [comment]
> @jengbou If original one is violating specification, Windows fsck should turn InUsed bit off of volume label entry that has 0 length...
> 

@namjaejeon I assume you meant Windows's chkdsk. Yes, so it seems it's an implementation choice rather than a violation. Whether one treats empty label as an active volume label entry or not dictates the InUse bit behavior. And it seems Windows creates empty label as inactive entry when formatting but allow active empty label when repairing. I guess it's a wishful thinking to get all tools to format drives in the same way for consistency. I have no issue if reverting back to original implementation make it more self consistent within Linux ecosystem.

**Comment by jengbou** [comment]
@YuezhangMo 

> @namjaejeon
> 
> > I would like to know how other exfat-utils format it. i.e. https://github.com/relan/exfat
> 
> exfat-utils set volume label to the first unused entry.
> 
> I tried the following cases.
> 
> 1. format without volume label, the first entry is set to 0x03.
> 2. add a new volume label, the volume label is set to the first entry.
> 3. remove the volume label, the entry type is set to 0x03, the other bytes are zeroed.
> 
> For the case of no volume label, I think it is better to set the first entry to 0x83, so that util-linux does not need to search the whole root directory, which will save a lot of time if the root directory is large.

So it seems other than setting it to 0x83, updating `exfat_set_volume_label()` to do similarly as exfat is also a viable alternative.

I am not saying that one should do so, but looking through root directory is sometimes necessary to find the correct label (e.g., when a drive history contains label altering actions on both Windows and Linux platforms). I would say one could consider implementing a new searching technique to replace single looping as a more prudent approach to improve the performance for those cases.

**Comment by namjaejeon** [comment]
@jengbou @YuezhangMo I decided to revert https://github.com/exfatprogs/exfatprogs/commit/cd1e21456fe6b8bf104b1da50210645baf0bdd26 patch. Thank you so much for sharing your great opinions and patches!

**Pull request closed without merging**
