### PR TITLE
For next

### PR DESCRIPTION
**Pull request by hclee**

### CODE REVIEW

**Comment by namjaejeon** [comment]
Applied, Thanks for your patches.

**Comment by namjaejeon** [comment]
> exfat2img -o - /dev/sda1 | bzip2 > sda1.dump.bz2

I tried to do dump exfat image using exfat2img. It doesn't work for me.
```
Bad fs_name in boot sector, which ...blablah..
```
but this command(exfat2img -o sda1.dump /dev/sda1) work fine.
Can you confirm exfat2img is working fine for you ?

**Comment by hclee** [comment]
> @hclee
> 
> > exfat2img -o - /dev/sda1 | bzip2 > sda1.dump.bz2
> 
> I tried to do dump exfat image using exfat2img. It doesn't work for me.
> 
> ```
> Bad fs_name in boot sector, which ...blablah..
> ```
> 
> but this command(exfat2img -o sda1.dump /dev/sda1) work fine. Can you confirm exfat2img is working fine for you ?

It works for me. Can you share the image for me to test it?

**Comment by namjaejeon** [comment]
Sure, I will do it tonight.

**Comment by namjaejeon** [comment]
[sda1.dump.tar.gz](https://github.com/exfatprogs/exfatprogs/files/9786641/sda1.dump.tar.gz)

This image is created using "sudo exfat2img -o sda1.dump /dev/sdb1" command.

**Comment by namjaejeon** [comment]
[sda1.dump_stdin.bz2.tar.gz](https://github.com/exfatprogs/exfatprogs/files/9786674/sda1.dump_stdin.bz2.tar.gz)

This image is created using "sudo exfat2img -o - /dev/sdb1 | bzip2 > sda1.dump_stdin.bz2"

To upload here, I have compressed bz2 file to tar.gz file again.

**Comment by hclee** [comment]
The dump created using stdin has no problem.
I have checked it the way below:
xfs_io -f -c "open" -c "truncate 1073741824" sda1.dump
bzip2 -dc sda1.dump_stdin.bz2 | exfat2img -o sda1.dump -
fsck.exfat sda1.dump

**Comment by namjaejeon** [comment]
> xfs_io -f -c "open" -c "truncate 1073741824" sda1.dump

We should do this command whenever dumping exfat image using stdin command ?

**Comment by namjaejeon** [comment]
exfat2img stdin dump doesn't support sparse. right ?

**Comment by hclee** [comment]
> > xfs_io -f -c "open" -c "truncate 1073741824" sda1.dump
> 
> We should do this command whenever dumping exfat image using stdin command ?

The dump created using stdin stores all metadata contiguously, and exfat2img layout the metadata into a partition or a image file. So we need to have a partition or a image file.

**Comment by namjaejeon** [comment]
exfat2img description is unclear to me in Readme, I think that it is same with other users. If we dump exfat image without stdin, how do we restore it to device file ?

**Comment by hclee** [comment]
> exfat2img stdin dump doesn't support sparse. right ?



> exfat2img description is unclear to me in Readme, I think that it is same with other users. If we dump exfat image without stdin, how do we restore it to device file ?

We have to use dd to restore filesystem from the dump created using stdin. Is it okay to append it into the exfat description?

**Comment by namjaejeon** [comment]
how does dd handle sparse space ? it seems to write zero data to device file ? I am wondering dd cause if restore speed is very low.

**Comment by hclee** [comment]
Yes, dd doesn't handle sparse space and the restoration is too slow.
I will check other utilities or have to implement the restoration option, --restore? for exfat2img. I will check it tomorrow.

**Comment by namjaejeon** [comment]
Okay, Thanks!

**Comment by hclee** [comment]
We have to implement the restore option, --restore.
exfat2img -r -o /dev/sdb1 sda1.sparse.dump or
bzip2 -dc sda1.stdin.dump.bz2 | exfat2img -r -o /dev/sdb1 -

**Comment by hclee** [comment]
I will change exfat like the above, what do you think of it?

**Pull request closed without merging**
