### PR TITLE
exfatprogs: Parsing VER to get major number

### PR DESCRIPTION
**Pull request by devidasjadhav**

### CODE REVIEW

**Comment by hclee** [comment]
Hello @devidasjadhav,

Could you add Signed-off-by in the commit message? You can refer to https://github.com/exfatprogs/exfatprogs/tree/exfat-next#contributor-information

**Comment by namjaejeon** [comment]
And he(@devidasjadhav) should add prefix(exfatprogs:) in subject...

**Comment by devidasjadhav** [comment]
Done.

**Comment by devidasjadhav** [comment]
edited commit message as well

**Comment by hclee** [comment]
@devidasjadhav 
You missed Signed-off-by. I have handled it at #124

**Pull request closed without merging**
