### PR TITLE
mkfs: add new option -q/--quiet

### PR DESCRIPTION
**Pull request by preichl**
This flag suppresses informative messages and prints only errors.

### CODE REVIEW

**Comment by namjaejeon** [comment]
Thanks for your patch:)

If user give -q -V option together, mkfs.exfat should show version ?

And Do you know why quiet option is needed ?

**Comment by preichl** [comment]
> Thanks for your patch:)

Thank you for comments!
> 
> If user give -q -V option together, mkfs.exfat should show version ?
It should,  of course.

I'll fix it in version 2, if you  consider the quiet option worthy at all..? 

> 
> And Do you know why quiet option is needed ?

Well, it is useful for scripts: xfs, ext4, btrfs they all have it...but of course there are workarounds.

**Comment by namjaejeon** [comment]
@preichl 

> Well, it is useful for scripts: xfs, ext4, btrfs they all have it...but of course there are workarounds.

Okay, Please send v2 patch:)

Thanks!

**Comment by namjaejeon** [comment]
Applied it to #exfat-next. Thanks for your patch!

**Pull request closed without merging**
