### PR TITLE
Manpage fixes debian lintian

### PR DESCRIPTION
**Pull request by hoexter**
While packaging exfatprogs for Debian our linter reported two minor issues with the manpages.

This PR is based on exfat-next and is geared to be merged into exfat-next.

### CODE REVIEW

**Comment by namjaejeon** [comment]
@hoexter You are missing signed-off-by in patches. Could you please add it ?

**Comment by hoexter** [comment]
> @hoexter You are missing signed-off-by in patches. Could you please add it ?

Sure, updated. Though I believe for none technical, mostly cosmetic changes that is a bit overkill. OTOH in the end it helps to keep track of contributors. :)

**Comment by dileks** [comment]
First patch has a typo s/Dbeian/Debian:

"Reported by lintian the Dbeian package linter"

**Comment by hoexter** [comment]
> "spelling fix in man 8 fsck.exfat" patch has a typo s/Dbeian/Debian:
> 
> "Reported by lintian the Dbeian package linter"

/me longs for a brown paper bag
Thanks, fixed that one as well.

**Comment by dileks** [comment]
Hehe.

BTW, for the above patch (both lintian warning reported via PM and here brown-paper bag)

Reported-by: Sedat Dilek <sedat.dilek@gmail.com>

**Comment by namjaejeon** [comment]
I added a prefix  and Reported-by tag to patches.(https://github.com/exfatprogs/exfatprogs/pull/116). I will push them to #exfat-next instead of this.
Thanks for your patches!!

**Comment by dileks** [comment]
Thanks for pushing this.

Sorry for being not precise enough.

My credits should only be for:
"manpages: remove spurious .TP at the end of man 8 tune.exfat"

Add it is missing surrounding "<...>" in the email-address (might be malformed/misinterpreted markdown syntax):
`Reported-by: Sedat Dilek <sedat.dilek@gmail.com>`

[1] https://github.com/exfatprogs/exfatprogs/commit/ea4f600b73ca483cfeb7d20ddca90db1aa15d962

**Comment by dileks** [comment]
Just as a hint:

I remember to run `codespell` on the Linux-kernel.

English is not my native language so I know it is hard to be correct.

[1] https://packages.debian.org/codespell
[2] https://github.com/codespell-project/codespell/

**Comment by dileks** [comment]
Run codespell:
```
$ codespell fs/exfat/*.c | grep -v iput
fs/exfat/namei.c:293: upto ==> up to
fs/exfat/nls.c:14: tabel ==> table

$ codespell fs/exfat/*.h 
fs/exfat/exfat_fs.h:133: usally ==> usually
```

**Comment by namjaejeon** [comment]
> Run codespell (here: Linux v5.8-rc4+):

@dileks  Okay, Thanks for your info. I will fix the typos.

**Comment by namjaejeon** [comment]
> My credits should only be for:
"manpages: remove spurious .TP at the end of man 8 tune.exfat"

@dileks Okay, I will do that. BTW,  I don't know exactly why your reported-by tag is added in this patch :)

**Comment by dileks** [comment]
I had some private-email (PM) exchange on the topic "exfat-utils VS. exfatprogs" with Sven Höxter in Debian.

When I have built a Debian package myself out of Sven's Git repository, I fell over the `lintian warning` and had reported this to him and he opened here a new (this) issue.
If you disagree with the `Reported-by` you can drop it.

Thanks to Sven (see [1]) we have progressed.

Please, feel free to correct the typos in `fs/exfat/` - and use codespell :-).

[1] https://ftp-master.debian.org/new/exfatprogs_1.0.3-1.html

**Comment by namjaejeon** [comment]
> Please, feel free to correct the typos in fs/exfat/ - and use codespell :-).
@dileks Okay! I will do that and Great news for releasing exfatprogs, Thanks for sharing and help! 

@hoexter Thanks for your work!

**Pull request closed without merging**
