### PR TITLE
exfatprogs: change Copyright holder in some files

### PR DESCRIPTION
**Pull request by hclee**
Change copyright holder from me to LG Electronics, because LG Electronics supports this work.

Signed-off-by: Hyunchul Lee <hyc.lee@gmail.com>

### CODE REVIEW

**Comment by hclee** [comment]
> You can add an Author beside copyright.

I have also appended Author.

**Comment by namjaejeon** [comment]
Probably you don't change all copyrights. e.g. fsck.c file and etc.., Is it right ?

**Comment by hclee** [comment]
> Probably you don't change all copyrights. e.g. fsck.c file and etc.., Is it right ?

I thought I had developed these on my extra time, but it is better to change its copyrights also. I will update these.

**Comment by namjaejeon** [comment]
If it's intentional, no problem. I will apply the current patch.

**Comment by namjaejeon** [comment]
@hclee Can you update how to use exfat2img in README and manpage also ?

**Comment by namjaejeon** [comment]
@hclee And need to update fsck.exfat also in README. And please check fsck.exfat manpage also.

**Comment by hclee** [comment]
> @hclee And need to update fsck.exfat also in README. And please check fsck.exfat manpage also.

Okay, I will.

**Pull request closed without merging**
