### PR TITLE
Exfat next

### PR DESCRIPTION
**Pull request by hclee**

### CODE REVIEW

**Comment by hclee** [comment]
안녕하세요 남재님,

깃허브에 1.0.4를 릴리즈 했는데 리뷰 부탁드립니다.
드래프트 상태에서 부탁했어야 했는데, 모르고 눌러버렸어요 ㅎㅎㅎ

감사합니다.

2020년 7월 31일 (금) 오후 1:48, Namjae Jeon <notifications@github.com>님이 작성:

**Comment by luca020400** [comment]
Nice work guys!
Been using it on AOSP with no problems so far :)

**Comment by namjaejeon** [comment]
@luca020400 Really thanks for your check!

**Comment by luca020400** [comment]
Hopefully it'll be adapted officially after an exfat enabled kernel is offered by default

**Comment by hclee** [comment]
> Hopefully it'll be adapted officially after an exfat enabled kernel is offered by default

@luca020400 Thank you! if there are any problems, please let us know thoses.

**Pull request merged**
