### PR TITLE
For next

### PR DESCRIPTION
**Pull request by hclee**

### CODE REVIEW

**Comment by namjaejeon** [comment]
Applied it to #exfat-next ! Let's start to prepare next version release.

**Comment by YuezhangMo** [comment]
Hi @hclee @namjaejeon 

The key word of 31d040ac210b37197c7db565cc0a1dcf7089cd24 should not be `ntfs`.

`read_file_dentry_set()` in exfat2img/exfat2img.c also has the out-of-bounds write.

**Comment by namjaejeon** [comment]
@namjaejeon Thanks for review. Fixed it in #exfat-next. thanks.

**Comment by hclee** [comment]
@YuezhangMo 
I did a PR for exfat2img also. Thank you.

**Pull request closed without merging**
