### PR TITLE
For next

### PR DESCRIPTION
**Pull request by hclee**

### CODE REVIEW

**Comment by namjaejeon** [comment]
@hclee Can you check it ?

**Comment by namjaejeon** [comment]
@luca020400 Hi, Could you please check the below change fix your build issue ?

```
-       exfat_debug("root cluster offset : %" PRIu64 "\n", root_clu_off);
+       exfat_debug("root cluster offset : %llu\n",
+                   (unsigned long long)root_clu_off);
```

**Comment by namjaejeon** [comment]
@luca020400 I remove this print line. If there is another issue on current master, Let me know it.
Thanks!

**Comment by luca020400** [comment]
This will do, thanks

**Pull request merged**
