### PR TITLE
 Fix endianness bugs and support test on big-endian

### PR DESCRIPTION
**Pull request by YuezhangMo**
These commits fix endianness bugs and support test on big-endian.

Difference from #269: "sudo" --> "sudo -E".

### CODE REVIEW

**Comment by aleasto** [comment]
Do you actually need sudo? I would think you don't, because `test_fsck.sh` by default acts on the img file without setting up loop devs (there is a switch in `test_fsck.sh` that controls this: `$NEED_LOOPDEV`)

**Comment by YuezhangMo** [comment]
Indeed, by default, sudo is not needed. I also didn't use sudo when testing in my side.
But if NEED_LOOPDEV is passed in the future, may add sudo but forgot to add option '-E'.

So I think it is better to use "sudo -E".

**Comment by namjaejeon** [comment]
Applied, Thanks!

**Comment by namjaejeon** [comment]
@aleasto Could you please confirm if this patch set fix your endian issues ?

**Comment by aleasto** [comment]
@namjaejeon Yes I can confirm the `fsck.exfat` tests now work in s390x. Thanks!

**Comment by hclee** [comment]
@aleasto 
I have released.

**Pull request closed without merging**
